# MSGM Configuration Default Template
#
# This file serves as a template for your local configuration.
# A copy will be created as msgm_config_local.yml when the package is loaded for the first time.
# You should edit msgm_config_local.yml to customize your settings, not this file.

# Default configuration values
default:
  YML2ENV_VERBOSE: FALSE       # TRUE/FALSE to enable verbose output
  YML2ENV_DEBUG: FALSE         # TRUE/FALSE to enable debug output
  YML2ENV_KING: "Renviron"


# Configuration variable descriptions
descriptions:
  YML2ENV_VERBOSE: "When set to TRUE, enables more detailed output for MSGM functions. Shows additional information about model operations, timing, and progress updates. Useful for understanding what the model is doing during execution."
  YML2ENV_DEBUG: "When set to TRUE, enables maximum diagnostic information: (i) runs gams code in debug mode; and (2) isplays detailed internal state, variable values, and step-by-step execution data. Use this when troubleshooting problems or developing new features."

